name: GITHUB_CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  
jobs:
  Ant_build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml
        
  sonarQubeTrigger:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: SonarQube_Scan
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: "/root/TestApplication"
          projectKey: "Github_CICD"
          projectName: "Github_CICD"
          projectVersion: "v0.0.1"
    
  archive-build-artifacts:
    runs-on: self-hosted
    steps:
      - name: Publishing_Artifacts
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }} 
          NEXUS_REPOSITORY_URL: ${{ secrets.NEXUS_REPOSITORY_URL }}
        run:  curl -v -u$NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file TestApplication.bar  $NEXUS_REPOSITORY_URL
  
  Deploying_app_in_openshift:
    runs-on: self-hosted
    steps:
    - name: docker login
      env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          OC_USERNAME: ${{secrets.OC_USERNAME}}
          OC_PASSWORD: ${{secrets.OC_PASSWORD}}
      run:  docker login -u $DOCKER_USERNAME --password $(oc whoami -t) default-route-openshift-image-registry.apps.ocp4.eidikointernal.com
    - name: Build the Docker image
      run: docker build -t devopsimage:v1 --file dockerfile . 
    - name: oc login,oc project,Docker tag & push
      run: |
            /usr/local/bin/ && ./oc login -u $OC_USERNAME -p $OC_PASSWORD --insecure-skip-tls-verify=true
            /usr/local/bin/ && ./oc project bharath
            docker tag devopsimage:v1 default-route-openshift-image-registry.apps.ocp4.eidikointernal.com/bharath/devops:v1
            docker push default-route-openshift-image-registry.apps.ocp4.eidikointernal.com/bharath/devops:v1
            /home/bandaru/Desktop/devshift.sh
